# Site settings
title: Yellow flash on Computing, Math and Beauty
email: minato.yellowflash.gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.yellowflash.in" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
